language: csharp
solution: Money/Money.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Money/Money.sln
after_script:
  - nunit-console Money.Test/bin/Release/Money.Test.dll